version: '3'

services:
  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./socket:/usr/src/app
    networks:
      - app-network
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
    links:
      - rabbitmq
    ports:
      - 8081:8081

  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./service:/usr/src/app
    networks:
      - app-network
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
    links:
      - rabbitmq
    ports: 
      - 8080:8080

  rabbitmq:
    image: rabbitmq:3.7.4
    networks:
      - app-network

networks:
  app-network:
    driver: bridge